name: GitHub Action - CTF - github backup
on: 
  push:
    branches:
      - main
  repository_dispatch:
    types: [ctf-github-backup-webhook]
jobs:
  ctf-github-backup-stage:
      if: >-
        github.event.client_payload.BY_CLI &&
        github.event.client_payload.IMPORT == false &&
        github.event_name == 'repository_dispatch'
      runs-on: ubuntu-latest
      env:
        MIGRATION_SCRIPT_FILE: migration-script/latest-space-migration-script.js
        MODEL_FILE: content-model/latest-model-space-cli.json
        ENTRIES_FILE: entries/latest-entries-space-cli.json
        CTF_CMA_KEY: ${{ secrets.CTF_CMA_KEY }}
      steps:
        - name: checkout repo
          uses: actions/checkout@v3

        - name: Install dependencies
          run: npm install -g contentful-cli

        - name: Contentful variables
          run: |
              echo "Using Contentful Space ${{ github.event.client_payload.CONTENTFUL_SPACE_ID }}"
              echo "Using Contentful Environment ${{ github.event.client_payload.CONTENTFUL_ENVIRONMENT_ID }}"
              
        - name: echo "Doing migration scripts"
          run: time -p contentful space --space-id ${{ github.event.client_payload.CONTENTFUL_SPACE_ID }} --mt ${{ env.CTF_CMA_KEY }} generate migration -f ${{ env.MIGRATION_SCRIPT_FILE }}
        
        - name: echo "Doing content model export"
          run: time -p contentful space --space-id ${{ github.event.client_payload.CONTENTFUL_SPACE_ID }} --mt ${{ env.CTF_CMA_KEY }} export --skip-roles --skip-webhooks --skip-content --skip-tags --content-file ${{ env.MODEL_FILE }}
            
        - name: echo "Doing content export"
          run: time -p contentful space --space-id ${{ github.event.client_payload.CONTENTFUL_SPACE_ID }} --mt ${{ env.CTF_CMA_KEY }} export --skip-roles --skip-webhooks --skip-content-model --skip-tags --content-file ${{ env.ENTRIES_FILE }}

        - name: Commit files
          run: |
              git config --global user.email "rodrigo.hal@ctf.com"
              git config --global user.name "Rodrigo HAL"
              git add ${{ env.MIGRATION_SCRIPT_FILE }}
              git add ${{ env.MODEL_FILE }}
              git add ${{ env.ENTRIES_FILE }}
              git commit -m "backup content model via actions"
        - name: Push changes
          run: git push
      
  ctf-github-import-stage:
    if: >-
      github.event.client_payload.BY_CLI &&
      github.event.client_payload.IMPORT &&
      github.event_name == 'repository_dispatch'
    runs-on: ubuntu-latest
    env:
      MIGRATION_SCRIPT_FILE: migration-script/latest-space-migration-script.js
      MODEL_FILE: content-model/latest-model-space-cli.json
      ENTRIES_FILE: entries/latest-entries-space-cli.json
      CTF_CMA_KEY: ${{ secrets.CTF_CMA_KEY }}
    steps:
      - name: checkout repo
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm install -g contentful-cli

      - name: Contentful variables
        run: |
            echo "Using Contentful Space ${{ github.event.client_payload.CONTENTFUL_SPACE_ID }}"
            echo "Using Contentful Environment ${{ github.event.client_payload.CONTENTFUL_ENVIRONMENT_ID }}"
            
      - name: echo "Importing migration scripts"
        run: time -p contentful space --space-id ${{ github.event.client_payload.CONTENTFUL_SPACE_ID }} --environment-id ${{ github.event.client_payload.CONTENTFUL_ENVIRONMENT_ID }} --mt ${{ env.CTF_CMA_KEY }} migration -y ${{ env.MIGRATION_SCRIPT_FILE }}
      
      - name: echo "Importing content model export"
        run: time -p contentful space --space-id ${{ github.event.client_payload.CONTENTFUL_SPACE_ID }} --environment-id ${{ github.event.client_payload.CONTENTFUL_ENVIRONMENT_ID }} --mt ${{ env.CTF_CMA_KEY }} import --skip-locales --skip-content-publishing --content-model-only --content-file ${{ env.MODEL_FILE }}
          
      - name: echo "Importing content export"
        run: time -p contentful space --space-id ${{ github.event.client_payload.CONTENTFUL_SPACE_ID }} --environment-id ${{ github.event.client_payload.CONTENTFUL_ENVIRONMENT_ID }} --mt ${{ env.CTF_CMA_KEY }} import --skip-content-model --skip-content-publishing --content-file ${{ env.ENTRIES_FILE }}


  ctf-github-backup-stage-script:
    if: >-
      github.event.client_payload.BY_CLI == false &&
      github.event.client_payload.IMPORT == false &&
      github.event_name == 'repository_dispatch'
    runs-on: ubuntu-latest
    env:
      MODEL_FILE: content-model/latest-model-space-script.json
      ENTRIES_FILE: entries/latest-entries-space-script.json
      CTF_CMA_KEY: ${{ secrets.CTF_CMA_KEY }}
    steps:
      - name: checkout repo
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm install contentful-export

      - name: Contentful variables
        run: |
            echo "Using Contentful Space ${{ github.event.client_payload.CONTENTFUL_SPACE_ID }}"
            echo "Using Contentful Environment ${{ github.event.client_payload.CONTENTFUL_ENVIRONMENT_ID }}"
      - name: echo "Script export content types"
        run: time -p node script/export.js ${{ github.event.client_payload.CONTENTFUL_SPACE_ID }} ${{ github.event.client_payload.CONTENTFUL_ENVIRONMENT_ID }} ${{ secrets.CTF_CMA_KEY }} ${{ env.MODEL_FILE }} 
            
      - name: echo "Script export content"
        run: time -p node script/export.js ${{ github.event.client_payload.CONTENTFUL_SPACE_ID }} ${{ github.event.client_payload.CONTENTFUL_ENVIRONMENT_ID }} ${{ secrets.CTF_CMA_KEY }} ${{ env.ENTRIES_FILE }} true
      
      - name: Commit files
        run: |
            git config --global user.email "rodrigo.hal@ctf.com"
            git config --global user.name "Rodrigo HAL"
            git add ${{ env.MODEL_FILE }}
            git add ${{ env.ENTRIES_FILE }}
            git commit -m "backup content model via actions using contentful-export"
      - name: Push changes
        run: git push

  ctf-github-import-stage-script:
    if: >-
      github.event.client_payload.BY_CLI == false &&
      github.event.client_payload.IMPORT &&
      github.event_name == 'repository_dispatch'
    runs-on: ubuntu-latest
    env:
      MODEL_FILE: content-model/latest-model-space-script.json
      ENTRIES_FILE: entries/latest-entries-space-script.json
      CTF_CMA_KEY: ${{ secrets.CTF_CMA_KEY }}
    steps:
      - name: checkout repo
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm install contentful-import

      - name: Contentful variables
        run: |
            echo "Using Contentful Space ${{ github.event.client_payload.CONTENTFUL_SPACE_ID }}"
            echo "Using Contentful Environment ${{ github.event.client_payload.CONTENTFUL_ENVIRONMENT_ID }}"
      - name: echo "Script import content types"
        run: time -p node script/import.js ${{ github.event.client_payload.CONTENTFUL_SPACE_ID }} ${{ github.event.client_payload.CONTENTFUL_ENVIRONMENT_ID }} ${{ secrets.CTF_CMA_KEY }} ${{ env.MODEL_FILE }} 
            
      - name: echo "Script import content"
        run: time -p node script/import.js ${{ github.event.client_payload.CONTENTFUL_SPACE_ID }} ${{ github.event.client_payload.CONTENTFUL_ENVIRONMENT_ID }} ${{ secrets.CTF_CMA_KEY }} ${{ env.ENTRIES_FILE }} true